robot_base_frame: base_footprint
publish_frequency: 1.0

obstacle_layer:
    footprint_clearing_enabled: false
    observation_sources: hokuyo_scan kinect_scan
    hokuyo_scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.75, raytrace_range: 4.0} #raytrace_range must be less than max range of sensor.
    kinect_scan: {data_type: LaserScan, topic: nav_kinect/scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 2.75, raytrace_range: 2.95} #raytrace_range must be less than max range of sensor.

inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 10.0

social_proxemic_layer:
     cutoff: 32
     amplitude: 95
     covariance: 0.25
     factor: 20.0

social_passing_layer:
     cutoff: 32
     amplitude: 95
     covariance: 0.25
     factor: 20.0

