sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_CONFIG='--no-install'  # work around kinova-ros install bug
    - UPSTREAM_WORKSPACE=file
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
# see: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out
install: travis_wait mvn install    # suggested timeout workaround
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
