robot_base_frame: base_footprint
publish_frequency: 1.0

# publish_voxel_map: true
#
# map_type: voxel
# origin_z: 0.0
# z_resolution: 0.2
# z_voxels: 10
# unknown_threshold: 10
# mark_threshold: 0

obstacles_costmap2d:
    footprint_clearing_enabled: false
    observation_sources: hokuyo_scan
    hokuyo_scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.75, raytrace_range: 4.0} #raytrace_range must be less than max range of sensor.

inflation:
    inflation_radius: 1.0
    cost_scaling_factor: 10.0

transform_tolerance:        0.1
robot_radius:               0.35
