#local_costmap:
#    global_frame:               /odom
#    robot_base_frame:           base_footprint
#    update_frequency:           10.0
#    publish_frequency:          10.0
#    rolling_window:             true
#    track_unknown_space:        false
#    static_map:                 false
#    resolution:                 0.025
#    transform_tolerance:        0.1
#    width: 7.0
#    height: 7.0
#    plugins:
#        - {name: obstacle_costmap2d,       type: "costmap_2d::ObstacleLayer"}
#        - {name: inflation,                 type: "costmap_2d::InflationLayer"}
local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 8.0
   height: 8.0
   resolution: 0.05
   transform_tolerance: 0.25
   footprint_padding: 0.0
   plugins:
      - {name: obstacle_costmap2d,         type: "costmap_2d::ObstacleLayer", output: "screen"}
      - {name: inflation,        type: "costmap_2d::InflationLayer", output: "screen"}
      - {name: social_proxemic_layer,        type: "social_navigation_layers::ProxemicLayer", output: "screen"}
     
