<?xml version="1.0"?>

<robot name="segbot"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find segbot_description)/urdf/segway_110_base.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/v3/common.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/v3/segbot_chassis.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/mounts/velodyne_mount.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/gazebo/segbot.gazebo.xacro" />

  <!-- Add the segbot base -->
  <xacro:segway_robot />
  <xacro:segbot_chassis parent="base">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}"/>
  </xacro:segbot_chassis>

  <!-- Add the velodyne -->
  <xacro:velodyne_mount name="velodyne" parent="back_left_vertical_beam">
    <origin xyz="0 0 ${14*INCH_TO_M}" rpy="${M_PI} 0 -${M_PI/2}" />
  </xacro:velodyne_mount>

  <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <odometryRate>100</odometryRate>
    </plugin>
  </gazebo>

</robot>
