<?xml version="1.0"?>

<robot name="segbot"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find segbot_description)/urdf/segway_110_base.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/v3/common.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/v3/segbot_chassis.urdf.xacro" />

  <!-- Add the segbot base -->
  <xacro:segway_robot />
  <xacro:segbot_chassis parent="base">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}"/>
  </xacro:segbot_chassis>

</robot>
